export const SET_SLOT = 'WP_JSON/SET_SLOT'
export const PUSH_TO_SLOT = 'WP_JSON/PUSH_TO_SLOT'
export const SET_CATEGORY = 'WP_JSON/SET_CATEGORY'
export const PUSH_TO_CATEGORY = 'WP_JSON/PUSH_TO_CATEGORY'
